### ISSUE TITLE
build: add a new action for validating the user scenarios

### ISSUE THREAD

**Issue by yorkie** [alibaba/pipcook#108]
We have received some feedback when using the CLI to initialize plugin development, so I think we need to add test cases for these specific user scenarios in addition to ensuring unit testing, I have compiled a list, if you need to add, you can also comment, too:

- [ ] Install Pipcook
- [ ] Initialize Pipeline Project
- [ ] Initialize Plugin Project
- [x] Run Pipeline Project
- [ ] Run Plugin Project

**Comment by FeelyChau** [comment]
No plugin in pipcook v2, this issue could be closed.
