### ISSUE TITLE
meta: define the spec of Pipcook Daemon

### ISSUE THREAD

**Issue by yorkie** [alibaba/pipcook#110]
We have introduced Pipcook Daemon at #30, now let's define the Pipcook Daemon in details.

- [ ] Define the declarative communication, and we have the following alternatives:
  - [x] HTTP
  - [ ] ~GRPC~
  - [ ] ~Node.js IPC (need to support for RPC mode)~
- [ ] Daemon SDK
  - [ ] Pipeline
    - [ ] CRUD, operations for pipeline
    - [ ] Run
    - [ ] Query
  - [ ] Plugin Management
    - [ ] Check, this checks if a plugin is able to install.
    - [ ] Install, this installs via the given plugin URI.
    - [ ] Run, this runs the given plugin with an input.
    - [ ] Test, this tests the given plugin with an input and expectations.
    - [ ] Log, this returns a readable stream for reading logs.
- [ ] CLI
  - [ ] Current implementation to use Daemon SDK.
  - [ ] Support for connecting to Pipcook Daemon remotely.
  - [ ] Support for Plugin Dist, including Plugin APIs and Plugin Pack.
- [ ] Internal works
  - [x] ML Metadata, for managing the Pipeline objects.(https://github.com/google/ml-metadata)
    - [x] Query Language:
      - [x] SQL, standard query language, and supported by many products like mysql, psql, sqlite and flink.
      - [ ] ~KV-based just like Redis and LevelDB, but more works to be done for applications.~
    - [x] Storage, we need 2 modes "local" and "remote" for standalone and distributed architecture.
      - [x] local: sqlite.
      - [x] remote: psql.
  - [ ] Pipeline IR
    - [ ] IR Specification
      - Root fields
        - Property "id", to specify the pipeline object.
        - Property "plugins" to config plugins.
      - Features
        - Easy to diff changes.
        - Easy to convert sequence for interrupter.
        - Pipeline Recovery must be supported.
    - [ ] VM
      - [ ] Interrupter for the IR
      - [ ] OP Code transfer to Plugin Internal Call
  - [ ] Plugin Internals.
    - [ ] PluginRT Bootstrap
      - [ ] Seed Process for speeding up.
      - [x] Lifecycle:
        - Create a runnable lock.
        - Initialize Boa Environment.
        - Install Python Dependencies.
        - Install PluginRT supporting files.
        - Call an *init* event to PluginRT.
        - Call plugin with an given input.
        - Release the runnable lock.
    - [ ] Plugin Internal Calls
      - [x] **0x30** start, this starts a new PluginRT process.
      - [x] **0x31** read, this reads an event from PluginRT.
      - [x] **0x32** write, this writes an event to PluginRT.
      - [ ] **0x100** compile, reversed for future AOT of PluginRT.
    - [x] Scheduler, this is for scheduling jobs for self-managed plugins and components.

**Comment by yorkie** [comment]
The daemon and costa has been completed :)
