### ISSUE TITLE
roadmap: v1.1.0

### ISSUE THREAD

**Issue by yorkie** [alibaba/pipcook#290]
There are the followings that we need in our next minor release 1.1.0:

- [x] Pipeline & plugin @rickycao-qy 
  - [ ] ~~more detailed API references which help plugin developer to work easier(#350 ).~~
  - [x] __more util functions based on the current builtin plugins(#306).__
  - [x] __introduce the stream-based pipeline, it decreases the cost of running a pipeline(#335 ).__
  - [ ] ~~provide a sandboxed file system for plugin developers.~~
- [x] Daemon internals @FeelyChau 
  - [x] __add plugin manager.__
  - [x] add JSSDK for Pipcook Daemon.
  - [x] resolve the SQLite migration issue when schemas are changed.
  - [ ] ~disallow the local mode to run pipeline and install plugins, using [import-maps](https://github.com/WICG/import-maps) instead.~
  - [ ] ~add Aliyun EAS output format.~
- [ ] Pipboard @yorkie 
  - [x] __a more flexible and easier user interface for configuring a pipeline.__
  - [x] remove the tfjs-node by running playground models in browsers(#297).
  - [x] __add plugin management.__
- [x] CI/CD @FeelyChau @yorkie 
  - [ ] ~~validation for all the pipelines.~~
  - [x] automatical nightly release.
  - [x] decrease the build time.
- [x] Models & algorithms @yorkie 
  - [ ] add BERT-based model plugins and pipeline, in which we could optimize the pre-trained-integrated pipeline.
    - [ ] add new Bert-based NER plugins and pipeline.
  - [x] __tutorial about writing a model plugin, it guides others to contribute model-related plugins.__
    - [x] add Python runtime to costa runnable.
- [ ] __Bugs & Issues__
  - [x] #277 plugin: the tfjs-based train plugin will be OOM because it reads all files into memory
  - [ ] #263 crushed when I run the output model.
  - [x] #261 plugin: data-process jimp.normalize is not the normalize
  - [x] #258 plugin: mnist-data-collect/image-data-process is too slow to handle data
  - [x] #249 daemon: how do we handle with the database migration
  - [x] #240 daemon: use randomBytes() instead of uuid

**Comment by Txiaozhe** [comment]
Could provide more use cases?

**Comment by Txiaozhe** [comment]
Or demo.

**Comment by Txiaozhe** [comment]
How about a complete demo for 'data collection -> training -> output a js module -> use this module as a app'？

**Comment by yorkie** [comment]
> Could provide more use cases?

Any suggestions in detail?

> How about a complete demo for 'data collection -> training -> output a js module -> use this module as a app'？

What do you mean bu the "app"?

**Comment by yorkie** [comment]
v1.1.0 has been release, closing.
