### ISSUE TITLE
meta: v1.0 roadmap

### ISSUE THREAD

**Issue by yorkie** [alibaba/pipcook#30]
The following is what exactly we want Pipcook v1 looks like:

<img width="613" alt="Screen Shot 2020-04-05 at 2 49 10 AM" src="https://user-images.githubusercontent.com/1935767/78458957-0c5af800-76e8-11ea-898d-4594fa3f5785.png">

We will introduce a new and unified layer for end-user that's so-called "Pipcook ML App", its goal is to simplify the developing machine learning applications, for more details you can go #33.

Now Pipcook is to be runtime for building ML applications, rather than a Node.js library. So we also make original pipcook-core to be a Daemon Process, it's used to operate plugins, and manage Pipelines via a new declarative language Pipeline IR.

To make sure what every plugin could run in more safety and powerful, Pipcook v1 is also to add the **Plugin Runtime**, which should be a standalone process/thread (via configuration), and there are the followings for plugin developers:

- ML API: it's the low-level machine learning APIs.
- Builtin Tensorflow.js library.
- Python APIs via Node.js lets you call other Python functions in JavaScript seamlessly.

Okay, let's see what the detailed v1 milestone tasks will be:

- [x] CI/CD workflow.
  - [x] pull request workflow.
  - [x] GitHub Actions.
  - [x] unit testing framework.
- [x] Solid documentation.
  - [x] refactoring documentation build scripts #39.
  - [x] tutorials includes: ML App, Pipeline and Plugin.
  - [x] typedoc includes: ML App APIs and Plugin APIs.
- [x] Experiment **ML App**
  - [x] definition of APIs and usage #33.
  - [x] pipelines generator for training/serving.
  - [ ] ~Pipboard supports running ML App.~
  - [ ] ~Pipboard supports preparing the dataset/samples.~
- [x] Stable **Pipeline**.
  - [x] decoupling the plugins at different stage.
  - [x] using a static DSL to represent a pipeline, and it's also the IR for the high-level ML App layer.
  - [x] refactoring for Pipcook daemon architecture for deploying online service.
    - [x] HTTP APIs.
    - [x] using HTTP APIs at CLI.
  - [x] preparing the v1 builtin plugins list and complete them.
- [x] Stable **Plugin** APIs, how to valid a plugin works.
  - [x] plugin specification.
  - [x] plugin runtime.
    - [x] provide the ml-base APIs.
    - [x] provide the bridge(boa) to Python's library.
- [x] Pipboard: a Web application for using Pipcook:
  - [ ] ~Pipboard Extension.~
  - [x] interactive GUI to CRUD pipelines.
  - [ ] ~plugin discovery and configuration.~
  - [x] ability to run pipeline.
  - [ ] ~ability to run ML App.~

**Comment by yorkie** [comment]
All v1.0 features are merged into master, we will have the formal release next week :p

**Comment by rickycao-qy** [comment]
v1.0 has been officially released.
