### ISSUE TITLE
v1.2.0 Roadmap

### ISSUE THREAD

**Issue by yorkie** [alibaba/pipcook#441]
There are the followings that we need in our next minor release 1.1.0:

- [x] Pipeline & plugin @rickycao-qy
  - [x] optimization of installing plugins(#477)
  - [ ] <s>optimization of initializing daemon</s>
  - [x] optimization of initlializing pipboard(#544)
- [x] Daemon internals @FeelyChau 
  - [ ] <s>controller test cases</s>
  - [ ] <s>fix boa crush</s>
- [x] Pipboard @yorkie 
  - [x] new design and interfaces.
  - [ ] <s>tensorboard integration.</s>
- [ ] CI/CD @FeelyChau
  - [ ] optimization of building.
  - [x] new design for the test flow. #437 
  - [x] full test for release
  - [ ] test all pipelines with minimal dataset and epoch
  - [x] migration test
- [x] Models & algorithms @yorkie 
  - [ ] <s>Text Summary</s>
  - [x] Bert-based NER(in Python)
- [x] __Bugs & Issues__
  - [ ] <s>#263 crushed when I run the output model.</s>

**Comment by yorkie** [comment]
@rickycao-qy @WenheLI @FeelyChau Please update your plans at 1.2.0, /cc @liangzr :)

**Comment by yorkie** [comment]
Closing this because we have released v1.2.0 :)
