### ISSUE TITLE
sdk: missing APIs for pipboard

### ISSUE THREAD

**Issue by yorkie** [alibaba/pipcook#490]
There are the following APIs which are required by new Pipboard

- common
  - [ ] ~~"ping/pong" to verify if the daemon is up.~~
  - [x] "versions" to return the current daemon version and others.
  - [x] "config" to return the following configurations: `npmRegistryPrefix`, `pythonIndexMirror` and `pythonCondaMirror`.
- plugin
  - [x] fetch plugin metadata #500
- pipeline
  - [x] list, missing the parameter `offset` and `limit` #501
- job
  - [x] list, missing the parameter `offset` and `limit` #501
  - [x] list by pipeline's id #501
  - [ ] ~~restart, [implementation](https://github.com/alibaba/pipcook/compare/optimize/pipboard#diff-8918917ece73065d78ac82c1b344110aR48)~~

**Comment by yorkie** [comment]
All tasks are done!
